In [44]:
import numpy as np

#1: Create x array with elements equal to 1.
x = np.ones((3, 3))

#2: Create y array with elements equal to 0.
y = np.zeros((3, 3))

#3: Add x and y arrays.
add_xy = x + y
print(add_xy)

#4: Print x array characteristics (e.g: dimension, shape, size, type)
print(x.shape)
print(x.size)
print(x.dtype)
print(x.ndim)

#5: Create a 2D array "called w"
w = np.array([[11,12],
              [13,14],
              [15,16]]) 

#6: Create z array contains the numbers from 1 to 3
z = np.arange(1,4)                   

#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray"
newArray = np.concatenate((z, w), axis=None).reshape(3, 3)
print(newArray)


#8: Print all elements of "newArray" using the loop.
for x in newArray.flat:
    print(x)

#9: Reverse the columns and rows of "newArray".
newArray = newArray.transpose()
print(newArray)


#10: Decrement all elements of "newArray" with 1.
newArray-=1
print(newArray)

#11: Find smallest and biggest values in "newArray".
print(np.max(newArray))
print(np.min(newArray))

#12: Print the first row of "newArray" using indexing.
print(newArray[0])

#13: Print the number equals 12 of "newArray" using indexing.
print(newArray[2,1])


#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.
print(newArray[(newArray == 0)])
print(newArray[(newArray == 13)])


#15: Change the shape of "newArray" to (9,1).
newArray= newArray.ravel()
print(newArray)

#16: Change the shape of "newArray" to (3,2).
newArray = np.resize(newArray, (3, 2))
print(newArray)

    

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)
9
float64
2
[[ 1  2  3]
 [11 12 13]
 [14 15 16]]
1
2
3
11
12
13
14
15
16
[[ 1 11 14]
 [ 2 12 15]
 [ 3 13 16]]
[[ 0 10 13]
 [ 1 11 14]
 [ 2 12 15]]
15
0
[ 0 10 13]
12
[0]
[13]
[ 0 10 13  1 11 14  2 12 15]
[[ 0 10]
 [13  1]
 [11 14]]
